### ISSUE TITLE
Lightning Inspector - error in Performance tab

### ISSUE THREAD

**Issue by RaguetOleap** [forcedotcom/lightning-inspector#16]
Hello
I just installed Lightning Inspector
The problem is that I see nothing in the performance tab.
When I click on the start button, there is a popup with this message : "Error clearing marks on inspected window"
I saw in the forum of the Chrome Webstore that other people had this problem, and I did not see any explication or resolution.
Would appreciate any help because I see in the Lightning Usage application that my Home page has bad response times and this is curious because it is mainly the standard home page.
![Lightning inspector](https://user-images.githubusercontent.com/58037361/69342770-90966c80-0c6c-11ea-9cc2-b08343076516.png)

**Comment by KrisGraySFDC** [comment]
Thanks for reaching out!

The Performance tab is an older part that we haven't been doing well on keeping up to date. 
Please use our actively developed alternative extension 
Salesforce Community Page Optimizer - https://chrome.google.com/webstore/detail/salesforce-community-page/alkcnclapbnefkodhbkpifdkceldogka

It works with all of Lightning, not just communities, and is a fantastic tool for diagnosing performance.

**Comment by RaguetOleap** [comment]
Thx !

it seems to be a great tool !
I will try it

**Comment by KrisGraySFDC** [comment]
FYI, I discovered that the APIs for the performance tab were taken out as part of the Open Source process. I've added them back in and the next release which should go out sometime later today should have fix the Performance tab.

We'll be officially deprecating it soon for the Communities Performance Optimizer though, so you really should be using that.

**Comment by KrisGraySFDC** [comment]
I manually verified this is working. Closing.
