### ISSUE TITLE
Component tree, Performance, Event Log tabs all seem not to be working 

### ISSUE THREAD

**Issue by londoner1234** [forcedotcom/lightning-inspector#17]
Hey All 
So it seems a few of the tabs aren't working correctly 

I seen a closed issue 
https://github.com/forcedotcom/lightning-inspector/issues/9

Which was describing something similar but is this released via the chrome extension or only part of the repro currently ? 

Thanks in advance

![image](https://user-images.githubusercontent.com/10601890/71003984-57211780-20d9-11ea-8458-f8942e1d539e.png)

![image](https://user-images.githubusercontent.com/10601890/71004596-0231d100-20da-11ea-8a6a-7a4d7cb29b1b.png)

![image](https://user-images.githubusercontent.com/10601890/71004616-065dee80-20da-11ea-8f8d-86004cf904eb.png)

**Comment by KrisGraySFDC** [comment]
Thanks for reporting this! I'm taking a look now. Will get back to you shortly.

**Comment by KrisGraySFDC** [comment]
CSS issue. Not quite sure how it wasn't an issue before, but I'm cleaning it up.

**Comment by KrisGraySFDC** [comment]
Hastily thrown together PR here 
https://github.com/forcedotcom/lightning-inspector/pull/18

Working on getting it reviewed and cleaned up.

**Comment by londoner1234** [comment]
Hey @KrisGraySFDC Greatly appreciate you looking into this and great news that it seemed a easy enough fix

**Comment by KrisGraySFDC** [comment]
I have merged my changes, and the CI should push an updated version to the chrome store soon.

**Comment by londoner1234** [comment]
Issue fixed https://github.com/forcedotcom/lightning-inspector/commit/cf3b3e2011b8a2f8c5e82809903d999573fac9d9
