### ISSUE TITLE
Lightning Inspector - Chrome v80 Actions Tab Visibility

### ISSUE THREAD

**Issue by kostadin-stoev** [forcedotcom/lightning-inspector#21]
Since the v80 release the action tab is no longer showing the running methods. However I inspect the panel I can see that the data exists. Its just not being rendered on the screen for some reason:

![image](https://user-images.githubusercontent.com/12606260/73938712-804b7080-48f0-11ea-8ecf-03b9dc169884.png)

**Comment by KrisGraySFDC** [comment]
Thanks @kostadin-stoev. I'll have to take a look in a few days unless someone else beats me to the PR.

**Comment by gikokopev** [comment]
@KrisGraySFDC  please fix this is the most useful tool for debugging lightning

**Comment by KrisGraySFDC** [comment]
Will try to take a look today. 

Looks like its trying to include a function in the payload which needs to be serializable. 

Do people not feel they have sufficient knowledge of the inspector to diagnose and send patches?

**Comment by gikokopev** [comment]
@KrisGraySFDC Ehm no? You realize that most salesforce developers are not developing chrome extensions right?
From my limited javascript knowledge I guess the problem would be the removal of support of v0 web components api in v80 of chrome. As the custom elements, shadow dom and html import is heavily used in the project my best try was to import the suggested v0.7.24 webcomponentsjs that supports v0 polyfills. Unfortunately this didn't help as the build with this library continued to throw all sorts of errors. As this version of the web component library is pretty much dead, and isn't expected to have any more fixes that was the farthest I was able to go.
Now that you know that someone actually tried to fix this to best of his abilities can you give a hand. It would be much appreciated.

**Comment by rochejul** [comment]
Hi @KrisGraySFDC 
I have a look on it locally and it seems using JSON.stringify before posting the message (and then using JSON.parse on the message event listener) should do the job to avoid the exception.

However, I have the feeling some tabs (like transactions and actions) seems to still have some issues.

For example, on transactions, I could not deactivate recording and I should click on the refresh button to see new transactions

If I have some cycles the next days, I will look on it deeper

Regards

**Comment by KrisGraySFDC** [comment]
Hey guys, thanks for the feedback here.

@gikokopev was right that its the usage of deprecated and removed web component api's that are hurting us here.

I'm working to move them to the new web components API. This work wasn't prioritized for the current "sprint" we're in. So I'm trying to fit it in where I can until the next sprint starts.

@rochejul the issue you're mentioning is separate and I think its because we're including a function in the window.postMessage().

That'll probably be a separate issue that I need to fix either through using JsonSerializer or just filtering out the functions.

**Comment by kostadin-stoev** [comment]
@KrisGraySFDC looks like you've resolved the majority of issues.
The only bug I can currently see is that the result data is not showing.

![image](https://user-images.githubusercontent.com/12606260/75660311-3b5af580-5c74-11ea-9649-c10e5b6ce07b.png)

**Comment by KrisGraySFDC** [comment]
Ahh Thanks Kostadin! 

I'll file a new bug for that.

**Comment by KrisGraySFDC** [comment]
Filed @W-7284394@

**Comment by KrisGraySFDC** [comment]
@kostadin-stoev The fix should be in the latest inspector. 1.0.6

**Comment by kostadin-stoev** [comment]
@KrisGraySFDC thanks! It works perfectly.
