### ISSUE TITLE
Component Tree not Displaying on Winter '20 orgs

### ISSUE THREAD

**Issue by jprichter** [forcedotcom/lightning-inspector#9]
The Component Tree is blank when attempting to view the Component tree in Winter '20 orgs. 

![screenshot](https://user-images.githubusercontent.com/974193/66484173-816cae00-ea74-11e9-9887-aafb493a13e4.png)

This error is showing in the Chrome Console.

`
AuraInspector: Failed to communicate to inspector. DOMException: Failed to execute 'postMessage' on 'Window': function(t){return"Sent: "+this.txTotalCount+" requests (i= "+this.txInstrCount+"); Size total= "+this.txTotalS...<omitted>...)} could not be cloned.
    at e (chrome-extension://pcpmcffcomlcjgpcheokdfcjipanjdpc/dist/LightningInspectorInjectedScript.js:1:20395)
`

**Comment by KrisGraySFDC** [comment]
Thanks @jprichter.

Looks like we're trying to serialize a function somehow, so its failing on us. Will diagnose.

**Comment by jprichter** [comment]
@KrisGraySFDC I was on the LEX home page, but the component tree was missing on any Lightning page I navigated to: list views, record detail, Lightning Tabs etc.

**Comment by KrisGraySFDC** [comment]
k thx

**Comment by KrisGraySFDC** [comment]
Pull request sent. Awaiting approval then will merge and push new version.

**Comment by KrisGraySFDC** [comment]
We have updated the extension. I tested it and it works on the component library. 

I'm going to close this now, but re-open if its still not working, or file new issues for any conditions you find that don't work.
